sudo: required

language: ruby

env:
  global:
  - secure: YOu6yITm3IkF2AoEAxw4ls7ZNhVjdXt0S1SmLaRMZiYNd94dCNdFJJB897LJwbmaE6UltZkRKAtJzw3OPiqN6MmaobBHV8ux8JIu3zHU7Vhs8PJ9R/dCVYXSQbaV4IcmJhc8h5Ob384cK51/YEOsWS44wKdmFeq0GFXN8S5jGdYqb1pAWOsqLoYS3kXXp9iG32aqEmnNxoFA9tx4a6oTC1e19ewJKEzTVY2ocMljzYvmBFVxH7TLEp/PGSLpvgE5JI3x2OaIV1xH+g291ztKQ1+CaMrQcU7Y7bcANFgoGqeUhuEN0pA0abQdffoAi0qeLfcu4bE8RBqWDPj+T7h8m42tmoDDMW2ezGJCV1Zk5MixWAn6FsPZNbsluZucdumLMy1AFxaiaM3UeueZ6eoclbiQ+8lsk1QKi/9FefNu42//5+Zt23xTEENZ4D1o7LsbRVA+MkyjLdfHvnYXOSEqECXO3vLT+dzJWXB4ui1jsuYuM2v9Ey28MsuyqPpQfnPG9boVd62yqVy2fA4LeysiQcLZPIr4xw1iz/b6mhZnf5SJdRfiCxu1dzWEzsr04+N6dcGKrQInb2njsqfC3Zmb+VcCtDMjeTSg1WmJ+qmcaqmjFlQt6YfrwDukBRKtTM2ewYI/pybyuIWAuSswvcfTIvl9HPyGuKrbCcRuS+EKpZQ=
  - secure: G3CbpMWA5K+laxykx10MjY9S9ZuUx8aQkOghw0tuIJfx6PKMVutISJ5zew2M39+omgeM18LsukDfVUFC/UcJcAR2XMRvWaLNWVhppTOD9ZjJ5GG55RLr5H0eP7gWcplLyyVc5C6Y+iTYNysvZFOXQsEYcYUNepdDIYLAsPHOX7lL6DXTE7uFhW2H3jXNewISRmVV1ik8DAdKl8jylxYTY58+R+ycQJ4cnNs5esj7TivhsILQf35djJtggo26k/xKXgU4jzv5s6LE38SDaA3rxGJHFD/1ujNmn2E1YXy2q394a6YeDIgBjmYdV+LzIgrEjcYOObgyW8a+tvIH8SiqSRyvYVb4Qe+g2cljh8H/cRrxMfEW0DcwwjYzPIY8fipoUNrz+fmq3+lf89msW3xHh2eVgidDKvN9pAX5uM015FkRLzTzhzI76HPGZIQXGAArPVvSMf4PkhGdNF+48vC+UnjIyfhcp+CJS+koygmqGf2lRYyveaox9uq57O4jduDrczNMET0lOU0THO5aBbLPJYHm9ZXmtcT1iDeThtfG6AZLznlMTBD+EQiqOKEoPYNXgtcb2nc1/RXe7i/YCfKJ5gsevtGPucj7/rBkgBXF1UCcfmfmGc0OwuVr5A2iSojCiNZ4ZCUjqhdMF6dejRxcb1sPVj9razfrFAsWMvc1Mz0=

services:
- docker

before_install:
- docker build -t cmr1/nginx-proxy .
- docker run -d -p 127.0.0.1:80:80 cmr1/nginx-proxy

script:
- "./test.sh"

after_success:
- "./deploy.sh"